# Section 1 : Importing torch

In [11]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [12]:
import torch

# Check if CUDA (NVIDIA GPU) is available
print("CUDA available:", torch.cuda.is_available())

# If CUDA is available, print details
if torch.cuda.is_available():
    print("Number of GPUs:", torch.cuda.device_count())
    print("Current GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("No GPU detected, running on CPU only.")

CUDA available: False
No GPU detected, running on CPU only.


# Section 2 : Introduction to tensors
Creating tensors

In [13]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [15]:
# Get tensor back as python int
scalar.item()

7

In [16]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
# Matrix
Matrix = torch.tensor([[7,8],
                       [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
Matrix.ndim

2

In [21]:
Matrix[0]

tensor([7, 8])

In [22]:
Matrix[1]

tensor([ 9, 10])

In [23]:
Matrix.shape

torch.Size([2, 2])

In [24]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Typical nomenclature
scalar - a
vector - y
matrix - Q
tensor - X

# Section 3 : Random tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers 

In [28]:
# create a random tensor of size/shape
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9941, 0.7861, 0.9808, 0.6012],
        [0.9370, 0.7227, 0.4711, 0.1189],
        [0.8072, 0.4346, 0.6242, 0.1387]])

In [29]:
random_tensor.ndim

2

In [30]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
torch.rand(size=(3, 3))

tensor([[0.3205, 0.1325, 0.2558],
        [0.3163, 0.2015, 0.1289],
        [0.4331, 0.0083, 0.2508]])

In [32]:
torch.rand(3, 3)

tensor([[0.0699, 0.6945, 0.5506],
        [0.4016, 0.5743, 0.5246],
        [0.9260, 0.4661, 0.5953]])

# Section 4 : Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

In [37]:
random_tensor.dtype

torch.float32

# Section 5 : Creating a range of tensors and tensors-like

In [38]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# Creating tensors like
tensors_zeros = torch.zeros_like(input=one_to_ten)
tensors_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Section 6 : Tensor datatypes

Note : Tensor dataypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right device

In [40]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor e.g float 32 or 16
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Section 7: Getting information from tensors (Tensors)

1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor, can use tensor.shape
3.Tensors not on the right device - to get device from a tensor, can use tensor.device 

In [46]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8947, 0.3439, 0.6157, 0.0563],
        [0.5521, 0.7201, 0.7270, 0.2285],
        [0.9392, 0.6517, 0.0081, 0.9462]])

In [47]:
some_tensor.shape

torch.Size([3, 4])

In [48]:
some_tensor.size()

torch.Size([3, 4])

In [49]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8947, 0.3439, 0.6157, 0.0563],
        [0.5521, 0.7201, 0.7270, 0.2285],
        [0.9392, 0.6517, 0.0081, 0.9462]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Section 8 : Manipulating Tensors (tensor operations)

Tensros operations include:
1.Addition
2.Subtraction
3.Multiplication (element-wise)
4.Division
5.Matrix multiplication

In [50]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [51]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [54]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [55]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Section 9 : Matrix Multiplication

Two main ways of performing multiplication is neural networks and deep learning.

Element-wise multiplication
Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1.The inner dimensions must match:
(3,2) @ (3,2) won't work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work

2.The resulting matrix has the shape of the outer dimensions
(2,3) @ (3,2) -> (2,2)
(3,2) @ (2,3) -> (3,3)

In [56]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
tensor @ tensor

tensor(14)

In [59]:
tensor

tensor([1, 2, 3])

In [60]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [61]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 578 μs


In [62]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 59.8 μs


tensor(14)

# Section 9 : One of the most common errors in deep learning: shape errors

In [63]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [11,12],
                        [9,13]])
#torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it is an alias for matmul)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [64]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7, 11,  9],
         [10, 12, 13]]),
 torch.Size([2, 3]))

In [65]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B.shape: {tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (same shape as above), tensor_B.T=torch.size([2, 3])")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(output.shape)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B.shape: torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (same shape as above), tensor_B.T=torch.size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
tensor([[ 27,  35,  35],
        [ 61,  81,  79],
        [ 95, 127, 123]])
torch.Size([3, 3])


# Section 10 : Finding the max, min, mean, sum, etc (tensor aggregation)

In [66]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [68]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [69]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [70]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [72]:
x[0]

tensor(0)

In [73]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [74]:
x[9]

tensor(90)

# Section 11 : Reshaping, stacking, squeezin and unsqueezing tensors

Reshaping - reshapes an input tensor to a defined shape

View - return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

squeeze - removes all '1; dimension from a tensor

unsqueeze - add a '1' dimension to a target tensor

permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [75]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [76]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [78]:
# Change the view
# shares the same memory
# changing z changes x
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [80]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# Section 12 : Squeezing, Unsqueezing and Permuting Tensors

In [81]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [82]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [83]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Section 13: Selecting Data From Tensors (indexing)

In [84]:
# Indexing with pytorch is similar to indexing with numpy

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [87]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [88]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [89]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [90]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

# Section 14 : PyTorch tensors and numpy

Numpy is a popular scientific python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

Data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)

Pytorch tensor -> numpy -> torch.tensor.numpy()

In [91]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's a default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
tensor.dtype

torch.float64

In [93]:
array.dtype

dtype('float64')

In [94]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Section 15 : Reproductibility (Taking the Random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again...

To reduce the randomness in neural networks and pytorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [97]:
torch.rand(3, 3)

tensor([[0.7653, 0.0937, 0.4658],
        [0.2047, 0.2006, 0.0193],
        [0.4548, 0.6349, 0.4137]])

In [98]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0667, 0.1919, 0.3788, 0.3304],
        [0.1766, 0.7118, 0.3185, 0.7494],
        [0.6368, 0.7999, 0.1958, 0.3944]])
tensor([[0.6491, 0.2832, 0.8796, 0.7825],
        [0.7526, 0.5563, 0.1785, 0.2026],
        [0.8065, 0.4135, 0.7605, 0.0412]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
# Set the random seed
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
